name: shackleton
description: A File System Explorer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0-alpha

environment:
  sdk: '^3.0.6'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.7
  async: ^2.11.0
  convert: ^3.1.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  exif: ^3.1.4
  file_icon: ^1.0.0
  flutter_riverpod: ^2.3.6
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  image: ^4.0.17
  intersperse: ^2.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  process_run: ^0.13.1
  riverpod_annotation: ^2.1.1
  sqflite_common_ffi: ^2.3.0
  super_context_menu: ^0.5.0
  super_drag_and_drop: ^0.5.0
  syncfusion_flutter_pdfviewer: ^22.2.7
  synchronized: ^3.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_lint: ^2.0.0
  riverpod_generator: ^2.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/explorer.png

flutter_launcher_icons:
  image_path: 'assets/explorer.png'
  remove_alpha_ios: true
  macos:
    generate: true
  android: false
  windows:
    generate: true
  ios: false
  web:
    generate: false
