name: Shackleton
description: A File System Explorer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_icon: ^1.0.0
  flutter_riverpod: ^2.3.6
  image: ^4.0.17
  intersperse: ^2.0.0
  url_launcher: ^6.1.11
  path: ^1.8.3
  path_provider: ^2.0.15
  process_run: ^0.13.0
  riverpod_annotation: ^2.1.1
  sqflite_common_ffi: ^2.2.5
  super_drag_and_drop: ^0.3.0+2

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/explorer.png

flutter_launcher_icons:
  image_path: 'assets/explorer.png'
  remove_alpha_ios: true
  macos:
    generate: true
  android: false
  windows:
    generate: true
  ios: false
  web:
    generate: false
