name: shackleton-macos-ci

on: [push, workflow_dispatch]
      
jobs:
 build:
   runs-on: macos-latest
   steps:
     - run: |
         - wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_darwin_arm64 -O yq
         - chmod o+rx yq
     - name: Get the app version
       id: get_version
       run: |
         ./yq '.version' pubspec.yaml
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
         cache: true
     - run: flutter config --enable-macos-desktop
     - run: dart run build_runner build --delete-conflicting-outputs
     - run: dart run flutter_launcher_icons
     - run: flutter build macos --release --no-tree-shake-icons
     - uses: QQxiaoming/create-dmg-action@v0.0.2
       with:
         name: 'shackleton-${{ steps.get_version.outputs.result }}'
         srcdir: 'build/macos/Build/Products/Release/shackleton.app'
     - uses: actions/upload-artifact@v1
       with:
         name: 'shackleton-${{ steps.get_version.outputs.result }}.dmg'
         path: 'shackleton-${{ steps.get_version.outputs.result }}.dmg'
