name: CI

on:
  push:
  pull_request:
    branches:
      - master
      
jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: arm64
         cache: true
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
