name: shackleton-linux-ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version:
            3.7
      - run: flutter config --enable-linux-desktop
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter pub run flutter_launcher_icons
      - run: flutter build linux --release --no-tree-shake-icons
      # Upload generated dmg to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: shackleton.zip
          path: build\linux\runner\Release\