name: shackleton-linux-ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get App version
        uses: mikefarah/yq@master
        with:
          cmd: echo "VERSION=$(yq .version pubspec.yaml)" >> $GITHUB_ENV
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ env.github-token }}
          tag:
            ${{ env.VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: false
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run flutter_launcher_icons
      - run: flutter build linux --release --no-tree-shake-icons
      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
          VERSION: ${{ env.VERSION }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: Shackleton-${{ env.VERSION }}-x86_64.AppImage
          files: Shackleton-${{ env.VERSION }}-x86_64.AppImage
          tag_name: ${{ env.VERSION }}
