name: shackleton-windows-ci

on: [push, workflow_dispatch]
      
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
         cache: true
     - run: flutter config --enable-windows-desktop
     - run: dart run build_runner build --delete-conflicting-outputs
     - run: flutter pub run flutter_launcher_icons
     - run: flutter build windows --release --no-tree-shake-icons
