name: shackleton-windows-ci

on: [push, workflow_dispatch]
      
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - name: Get the app version
       id: get_version
       run: |
         choco install yq
         echo "VERSION=$(yq .version pubspec.yaml)" >> $GITHUB_ENV
     - name: "Push tag from pubspec.yaml"
       uses: EndBug/latest-tag@latest
       with:
         tag-name: ${{ env.VERSION }}
     - name: Load certificate
       shell: powershell
       run: |
         pwd
         echo ${{ secrets.certificate }} | base64 -d > sharpblue.pfx
         dir sharpblue.pfx
     - run: flutter config --enable-windows-desktop
     - run: dart run build_runner build --delete-conflicting-outputs
     - run: dart run flutter_launcher_icons
     - run: flutter build windows --release --no-tree-shake-icons
     - run: dart run msix:create --certificate-path .\sharpblue.pfx
     - name: Create Release
       uses: softprops/action-gh-release@v0.1.15
       with:
         name: 'shackleton-${{ env.VERSION }}'
         files: build/windows/runner/Release/shackleton.msix
         tag_name: ${{ env.VERSION }}
