name: shackleton-windows-ci

on: [push, workflow_dispatch]
      
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - run: flutter config --enable-windows-desktop
     - run flutter pub add --dev msix
     - run: dart run build_runner build --delete-conflicting-outputs
     - run: dart run flutter_launcher_icons
     - run: flutter build windows --release --no-tree-shake-icons
     - run: dart run msix:create

     # Upload generated dmg to the artifacts.
     - uses: actions/upload-artifact@v1
       with:
        name: shackleton.msix
        path: build/windows/runner/Release/shackleton.msix
