name: shackleton-windows-ci

on: [push, workflow_dispatch]
      
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - name: Set up .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x # Adjust as needed

     - name: Install WiX Toolset
       run: |
         Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip' -OutFile 'wix311-binaries.zip'
         Expand-Archive -Path 'wix311-binaries.zip' -DestinationPath 'C:\wix311'
         Add-Content -Path $env:GITHUB_PATH -Value 'C:\wix311'
       shell: powershell
     - run: flutter config --enable-windows-desktop
     - run: dart run build_runner build --delete-conflicting-outputs
     - run: dart run flutter_launcher_icons
     - run: flutter build windows --release --no-tree-shake-icons

     - name: Build MSI
       run: |
         candle shackleton.wxs -o shackleton.wixobj # Compile your WiX source file
         light shackleton.wixobj -o shackleton.msi # Link your MSI package

     # Upload generated dmg to the artifacts.
     - uses: actions/upload-artifact@v1
       with:
        name: shackleton
        path: shackleton.msi
